name: 'Hangar Upload Action'
description: 'Upload Minecraft plugins to Hangar (PaperMC) with comprehensive file and dependency management'

branding:
  icon: 'upload'
  color: 'gray-dark'

inputs:
  api_token:
    description: 'Hangar API token for authentication (generate from your Hangar profile settings)'
    required: true

  slug:
    description: 'Project slug/identifier on Hangar (e.g., "my-awesome-plugin")'
    required: true

  version:
    description: 'Plugin version string (e.g., "1.0.0", "2.1.3-SNAPSHOT")'
    required: true

  channel:
    description: 'Release channel type (e.g., "Release", "Beta", "Alpha", "Snapshot")'
    required: true

  files:
    description: |
      JSON array of files to upload. Each file must specify:
      - platforms: Array of ["PAPER", "VELOCITY", "WATERFALL"]
      - Either: path (glob pattern for local files) OR url + externalUrl for external files
      
      Example:
      [
        {
          "path": "build/libs/*.jar",
          "platforms": ["PAPER"]
        },
        {
          "path": "**/build/libs/!(*-sources|*-javadoc).jar",
          "platforms": ["VELOCITY"]
        },
        {
          "url": true,
          "externalUrl": "https://example.com/plugin.jar",
          "platforms": ["PAPER", "VELOCITY"]
        }
      ]
    required: true

  description:
    description: 'Markdown-formatted release description/changelog'
    required: false
    default: ''

  plugin_dependencies:
    description: |
      JSON object mapping plugin names to version ranges
      Example: {"WorldEdit": "7.2.15", "Vault": "1.7.3"}
    required: false
    default: '{}'

  platform_dependencies:
    description: |
      JSON object mapping platform names to version patterns. Supports semver-like patterns for PAPER platform only.
      PAPER versions are resolved from Mojang's official API.
      
      Supported patterns for PAPER:
      - Exact: ["1.20.1", "1.19.4"]  
      - Range: [">=1.19.0"]
      - Patch: ["~1.20.0"] (1.20.x versions)
      - Compatible: ["^1.19.0"] (1.19+ versions)
      - Wildcard: ["1.20.x"]
      
      VELOCITY/WATERFALL use exact versions only:
      Example: {"PAPER": [">=1.19.0"], "VELOCITY": ["3.2.0"], "WATERFALL": ["1.19"]}
    required: false
    default: '{}'

outputs:
  upload_url:
    description: 'Direct URL to the uploaded version page on Hangar'

runs:
  using: 'node20'
  main: 'dist/index.js'
