name: 'Hangar Upload Action'
description: 'Upload minecraft plugin to hangar.papermc.io with github actions!'

branding:
  icon: 'upload'
  color: 'gray-dark'

inputs:
  api_token:
    description: 'Hangar API Token'
    required: true
  slug:
    description: 'Plugin Name'
    required: true
  version:
    description: 'Plugin Version'
    required: true
  channel:
    description: 'Channel type of the release'
    required: true
  files:
    description: 'Files to upload'
    required: true
  description:
    description: 'Release description'
    required: false
    default: ''
  plugin_dependencies:
    description: 'Plugin dependencies'
    required: false
    default: '{}'
  platform_dependencies:
    description: 'Platform dependencies'
    required: false
    default: '{}'

runs:
  using: 'node20'
  main: 'dist/index.js'
