name: Update major version tag

on:
  push:
    tags:
      - "v*"

jobs:
  update_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows updating tags

    steps:
      - uses: nowactions/update-majorver@v1